owner: familio-org
repo: health

sites:
  - name: Familio
    url: https://familio.org/surnames
    expectedStatusCodes:
      - 200
      - 403
  - name: Familio Maps
    url: https://maps.familio.org/health

status-website:
  baseUrl: /health
  name: Familio Хэлфчек

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
