owner: familio-org
repo: health

sites:
  - name: Familio Maps
    url: https://maps.familio.org/health
  - name: Familio GEDCOM
    url: https://gedcom.familio.org

status-website:
  baseUrl: /health
  name: Familio Хэлфчек

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
