# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Familio
    url: https://familio.org/surnames
  - name: Familio Maps
    url: https://maps.familio.org/health

status-website:
  baseUrl: /health
  name: Familio Хэлфчек
