owner: familio-org
repo: health

sites:
  - name: Familio
    url: https://familio.org/surnames
  - name: Familio Maps
    url: https://maps.familio.org/health

status-website:
  baseUrl: /health
  name: Familio Хэлфчек
