owner: familio-org
repo: health

sites:
  - name: Familio
    url: https://familio.org/surnames
    headers:
      - "Sec-Fetch-Dest: document"
      - "Sec-Fetch-Mode: navigate"
      - "Sec-Fetch-Site: none"
      - "Sec-Fetch-User: ?1"
      - "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3.1 Safari/605.1.15"
  - name: Familio Maps
    url: https://maps.familio.org/health

status-website:
  baseUrl: /health
  name: Familio Хэлфчек

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
