owner: familio-org
repo: health

sites:
  - name: Familio Maps
    url: https://maps.familio.org/health
  - name: Familio GEDCOM
    url: https://gedcom.familio.org
  #- name: Familio GEDCOM
  #  url: https://familio.org/api/v1/healthcheck
  #  url: https://familio.org/surnames

status-website:
  baseUrl: /health
  name: Familio Хэлфчек

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
