owner: familio-org
repo: health

sites:
  - name: Familio Maps
    url: https://maps.familio.org/health
    expectedStatusCodes:
      - 200
      - 0
  - name: Familio GEDCOM
    url: https://gedcom.familio.org
    expectedStatusCodes:
      - 200
      - 0
  - name: Familio API
    url: https://familio.org/api/v1/healthcheck
    expectedStatusCodes:
      - 200
      - 0
      - 403
  - name: Familio
    url: https://familio.org/surnames
    expectedStatusCodes:
      - 200
      - 0
      - 403

status-website:
  baseUrl: /health
  name: Familio Хэлфчек

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
